apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
#      kubeProxyReplacement: "strict"
#      k8sServiceHost: 10.0.2.15
#      k8sServicePort: 6443
      operator:
        replicas: 1
      encryption:
        enabled: false
        type: wireguard
      l7Proxy: false
      hubble:
        metrics:
          enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
        relay:
          enabled: true
        ui:
          enabled: true
          replicas: 1
#          ingress:
#            enabled: true
#            hosts:
#              - hubble.k8s.intra
#            annotations:
#              cert-manager.io/cluster-issuer: ca-issuer
#            tls:
#            - secretName: ingress-hubble-ui-tls
#              hosts:
#              - hubble.k8s.intra
#      prometheus:
#        enabled: true
#        # Default port value (9090) needs to be changed since the RHEL cockpit also listens on this port.
#        port: 19090
#        # Configure this serviceMonitor section AFTER Rancher Monitoring is enabled!
#        #serviceMonitor:
#        #  enabled: true        
