apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: cattle-system
spec:
  chart: https://github.com/longhorn/charts/releases/download/longhorn-1.3.2/longhorn-1.3.2.tgz
  targetNamespace: longhorn-system
  valuesContent: |-  
    defaultSettings:
      defaultReplicaCount: 1
      replicaSoftAntiAffinity: true
