write-kubeconfig-mode: "0644"
selinux: true
token: RKE2_TOKEN
data-dir: RKE2_DATA_PATH
#server: https://ENV-DOMAIN:9345
tls-san:
  - ENV-DOMAIN
cluster-domain: "ENV-DOMAIN"  
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"  
node-label:
  - "nodetype=master"  
cni:
  - cilium
disable:
  - rke2-canal
  - rke2-kube-proxy
  - rke2-ingress-nginx
#ingress:
#  provider: nginx
#  options:
#    use-forwarded-headers: "true"
#    allow-snippet-annotations: "false"
#    compute-full-forwarded-for: "true"
