apiVersion: v1
kind: Namespace
metadata:
  name: cattle-resources-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-backup-crd
  namespace: kube-system
spec:
  chart: rancher-backup-crd
  repo: https://charts.rancher.io
  targetNamespace: cattle-resources-system
  version: 3.0.0
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-backup
  namespace: cattle-resources-system
spec:
  chart: rancher-backup
  repo: https://charts.rancher.io
  targetNamespace: cattle-resources-system
  version: 3.0.0
  valuesContent: |-
    persistence:
      enabled: true
      size: 20Gi
      storageClass: longhorn
---
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: backup-rancher
  namespace: cattle-resources-system
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 10
  schedule: 0 00,12 * * *
