apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  version: CHART_RANCHER_VERSION #ex 2.7.6  # specify the chart version here
  targetNamespace: cattle-system
  repo: https://releases.rancher.com/server-charts/stable
  valuesContent: |-
    bootstrapPassword: defaultSecret12345
    tls: external
#    antiAffinity: required
