apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  chart: https://rke2-charts.rancher.io/assets/rke2-ingress-nginx/rke2-ingress-nginx-4.6.101.tgz
  valuesContent: |-
    controller:
      config:
        allowSnippetAnnotations: "false"
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"

       
